# Generated by Django 5.1.3 on 2024-11-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_catastro', models.CharField(max_length=20, unique=True)),
                ('municipio', models.CharField(max_length=50)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='productores.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('tipo_cultivo', models.CharField(max_length=50)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viveros', to='productores.finca')),
            ],
        ),
    ]
